#!/bin/sh
#
# git-worker init file for git-worker daemon
#
# chkconfig: - 65 35
# description: gitolite config worker
# processname: git-worker.py
# config: /etc/bugit/settings
# pidfile: /var/run/git-worker.pid

. /etc/rc.d/init.d/functions

name="git-worker.py"
exec="/usr/bin/$name"
pidfile='/var/run/git-worker.pid'
config='/etc/bugit/settings'

start() {
    [ -f $config ] || exit 6
    [ -x $exec ] || exit 5
    echo -n $"Starting $name"
    daemon "$exec"
    retval=$?
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    killproc -p $pidfile $name
    retval=$?
    echo
    return $retval
}

restart() {
    stop
    start
}

reload() {
    false
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        rh_status_q && exit 7
        $1
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
exit $?

